version: '3.8'
services:
  adguard:
    container_name: adguard
    image: lolgast/adguard-unbound
    volumes:
      - ./adguard-work:/opt/adguardhome/work
      - ./config:/opt/adguardhome/conf 
      - ./unbound:/opt/unbound 
    ports:
      - "53:53/tcp"
      - "53:53/udp"
        #      - "5443:5443/tcp"
        #      - "3000:3000/tcp" 
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  default:
    external:
      name: reverse-proxy
